### ISSUE TITLE
Problem with created images

### ISSUE THREAD

**Issue by deman2660** [dawmro/teller_of_tales#1]
All the images are black so i dont think its generating them.
I'm not sure what is causing this so any help or suggestions would be appreciated. The videos have subtitles but its just subtitles on a black background.

https://github.com/dawmro/teller_of_tales/assets/73039800/c4510a8f-52d4-42a0-8177-21717da41f6e

**Comment by dawmro** [comment]
1. If you are running local install:

First think that comes to mind is NSFW_filter turned ON `NSFW_filter = yes,` but it shouldn't make all images black unless you are trying to make a porn video. If this is not the case, then there might be something wrong with your pytorch install or ImageMagic install.

You might try to pick different model in "config.ini" file, `model_id = darkstorm2150/Protogen_v2.2_Official_Release` works fine for me, but who knows.
To check if it's problem with models downloaded from hugginface is to switch `USE_SD_VIA_API = yes`. That way you will be able to generate images using AUTOMATIC1111 running in api mode. To run AUTOMATIC1111 in api mode set `set COMMANDLINE_ARGS=--api` in "stable-diffusion-webui\webui-user.bat".



2. If you are running GoogleColab version:

You need to provide your own `openai.api_key`, the one in the file does not work.
To be honest, I haven't used the Colab version since April when my OpenAI account ran out of credit.

**Comment by deman2660** [comment]
Using AUTOMATIC1111 in api mode fixed the problem, thank you
